const busyMessage = {
  messages: [
    "Sorry, I am busy now... Please try again later!!!",
    "I’m currently occupied with something incredibly important... like staring at the wall.",
    "Busy? Oh, you mean my favorite hobby? Please try again later!!!",
    "I’d love to chat, but I’m currently in a deep relationship with my to-do list.",
    "Sorry, I can’t right now—my schedule is packed with doing absolutely nothing.",
    "I’m busy! Just me, myself, and my overwhelming procrastination.",
    "Oh, I wish I could help, but I’m currently tied up in a very important meeting with my couch.",
    "I appreciate your enthusiasm, but I’m currently busy avoiding responsibilities!",
    "Busy now? Absolutely! Just me and my very intense Netflix marathon.",
    "Sorry, can’t talk! I’m currently in a staring contest with my cat.",
    "Oh, I’m swamped with important tasks right now—like scrolling through memes.",
    "I’m busy! Please hold while I pretend to be productive.",
    "Sorry, but my calendar is full of ‘me time.’ Try again later!",
    "I’m engaged in a very important conversation with my coffee.",
    "I’d love to, but I’m busy—improving my napping skills!",
    "Sorry, I’m currently too busy being fabulous to chat.",
    "I’m occupied! If only I could clone myself... or just take a nap.",
    "I can’t right now; I’m too busy being a master of multitasking—at nothing.",
    "I’m busy with my latest project: extreme daydreaming.",
    "Sorry, I can’t! I’m currently busy pretending to be a functioning adult.",
    "I’m in the middle of an important project—contemplating life choices.",
    "Can’t chat! I’m busy making bad decisions. Please try again later!",
    "Oh, I’m overwhelmed with being unproductive at the moment.",
    "Sorry, but I’m currently busy perfecting the art of avoiding everything.",
    "I’m busy! My schedule is filled with vital ‘me’ time.",
    "I’d love to talk, but I’m in a committed relationship with my couch.",
    "I’m tied up right now—physically and metaphorically.",
    "I’m busy with my very important ‘not now’ agenda!",
    "Sorry, I’m engaged in a thrilling adventure... of doing nothing.",
    "I’m busy! Just me and my favorite procrastination techniques.",
    "Oh, I’m currently busy with my ongoing battle against productivity.",
    "I can’t talk right now; I’m busy contemplating the mysteries of the universe... or my snacks.",
    "I’d chat, but I’m currently wrapped up in some very serious daydreaming.",
    "Sorry, I’m in the middle of an important conversation with myself.",
    "I’m busy right now! Can’t you see I’m prioritizing my daydreams?",
    "I’d love to help, but my schedule is packed with ‘me’ time.",
    "Sorry, but I’m currently focused on my next snack.",
    "I’m currently preoccupied with... well, nothing important.",
    "I can’t talk! I’m busy counting the seconds until my next snack break.",
    "Oh, I’m occupied with very important matters—like perfecting my nap.",
    "Sorry, my schedule is full of ‘please leave me alone’ moments.",
    "I’m busy! Just me and my ongoing struggle with productivity.",
    "I can’t chat right now; I’m busy contemplating what to eat next.",
    "Sorry, I’m currently swamped with my very important nap schedule.",
    "I’d chat, but I’m in a deep conversation with my favorite snacks.",
    "I’m busy! My schedule is full of highly important nothings.",
    "I can’t talk right now; I’m busy mastering the art of doing nothing.",
    "Sorry, I’m currently too busy being fabulous to engage.",
    "I’m busy! My schedule is packed with essential ‘me time’.",
    "I’d love to help, but I’m currently engaged in the fine art of procrastination.",
    "Sorry, but I’m in the middle of a very important staring contest with my cat.",
    "I’m busy! Just me and my overwhelming desire to do nothing.",
    "I can’t right now; I’m busy contemplating what to binge-watch next.",
    "Oh, I’m occupied with my latest project: extreme couch lounging.",
    "I’m busy! Please hold while I prioritize my snack selection.",
    "Sorry, I’m currently busy avoiding all responsibilities.",
    "I’d love to talk, but I’m busy—improving my napping skills!",
    "I’m in the middle of an urgent conversation with my snacks.",
    "I can’t talk right now; I’m busy perfecting my napping techniques.",
    "Sorry, but I’m currently busy avoiding all adulting tasks.",
    "I’m busy! Just me and my favorite procrastination techniques.",
    "I can’t talk! I’m currently swamped with deep thoughts about snacks.",
    "Oh, I’m engaged in an important quest for ultimate relaxation.",
    "Sorry, I’m currently busy with the very important task of daydreaming.",
    "I’m busy! My schedule is filled with vital ‘me’ time.",
    "I’d love to help, but I’m busy—improving my napping skills!",
    "Sorry, I can’t right now; I’m busy perfecting the art of doing nothing.",
    "I’m occupied! Please hold while I pretend to be productive.",
  ],
};

const getRandomMessage = () => {
  const messages = busyMessage.messages;
  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
};

export default getRandomMessage;
