// sarcasticMessages.js
const sarcasticMessages = {
  messages: [
    "Ding! Looks like time has finally caught up with us. How original!",
    "Well, the timer says it’s over. Guess we’ll just pretend that was a success!",
    "Time’s up! What a shocker! I was just getting comfortable.",
    "And just like that, the timer has made its grand exit. Bravo!",
    "Guess what? The timer didn’t lie! It’s officially time to stop pretending we know what we’re doing.",
    "Ding, ding! Time’s up! Hope you enjoyed the ride—because the exit is right over there.",
    "Congratulations! The timer has declared us done—how inspiring!",
    "Oh look, the timer’s going off—how convenient for our nonexistent plans!",
    "Surprise! The timer is done, and so are our dreams for productivity!",
    "Well, time’s up! Who knew minutes could be this disappointing?",
    "Ding! The timer thinks it’s the boss of us now!",
    "And there it is—the timer’s grand announcement! How thrilling!",
    "Guess what? The timer just became my least favorite person.",
    "Time’s up! What an exciting way to end absolutely nothing!",
    "Ding! The timer has spoken! How utterly riveting!",
    "Well, time’s up! Who needs goals when you have a timer?",
    "Congratulations! The timer has declared a winner—definitely not us!",
    "Ding! Time’s over! Let’s all pretend we had a good time!",
    "Well, look at that! The timer thinks it knows what’s best for us!",
    "And just like that, the timer takes center stage! How wonderful!",
    "Ding! Time’s up! I hope you enjoyed your brief moment of joy!",
    "Well, well, well… the timer thinks it has authority over our lives!",
    "Ding! Time’s over! Let’s all bask in the glory of unmet expectations!",
    "Congratulations! The timer has declared us all out of luck!",
    "And just like that, the timer has made us all question our choices!",
    "Ding! Time’s up! Can we get a round of applause for my non-existent plans?",
    "Well, look at that! The timer is here to remind us of our limitations!",
    "Ding! Time’s over! What a grand finale to our mediocrity!",
    "Congratulations! The timer has put an end to our wild aspirations!",
    "Oh, look! The timer thinks it’s the star of the show today!",
    "Ding! Time’s up! Let’s all take a moment to reflect on our failures!",
    "And there it is—the timer’s epic declaration! How thrilling!",
    "Well, well, the timer has made its presence known once again!",
    "Time’s up! I guess that’s it for our grand adventure!",
    "Ding! The timer has come to ruin our plans—how refreshing!",
    "And just like that, the timer steals our thunder! How charming!",
    "Well, time’s up! Can I get a round of applause for disappointment?",
    "Ding! Time’s over! Let’s all pretend this never happened!",
    "Congratulations! The timer has declared us done! How empowering!",
    "Well, the timer has decided we’ve had enough fun. Thanks for that!",
    "Ding! Time’s up! I guess we’ll all just sit here in silence now!",
    "And just like that, the timer has thrown a wrench in our plans!",
    "Ding, ding! The timer thinks it can just waltz in and take over!",
    "Well, well, the timer has officially called it quits—how shocking!",
    "Time’s up! Who knew this would turn into a race against the clock?",
    "Ding! The timer has come to ruin our plans once more!",
    "And just like that, the timer has declared our efforts utterly futile!",
    "Ding! Time’s up! Can we get a round of applause for our wasted time?",
    "Congratulations! The timer has declared our efforts officially wasted!",
    "Ding! The timer thinks it knows what’s best for us! How sweet!",
    "Well, look at that! The timer is here to remind us we’re out of time!",
    "Time’s up! I hope you enjoyed that fleeting moment of joy!",
    "Ding! Time’s over! Let’s all pretend we were super productive!",
    "Well, the timer has decided we’ve had enough fun. How rude!",
    "Ding! The timer is here to ruin our plans! How delightful!",
    "Congratulations! The timer just gave us the gift of disappointment!",
    "And just like that, the timer has betrayed our expectations!",
    "Ding! Time’s up! Who knew this would be so anticlimactic?",
    "Well, well, the timer has arrived to put an end to our fun!",
    "Time’s up! Let’s all stand in silent defeat!",
    "Ding! The timer thinks it has the final word—how charming!",
    "Congratulations! The timer has declared us all out of luck!",
    "Ding! Time’s up! What a plot twist—said no one ever!",
    "Well, look at that! The timer is here to remind us of our failures!",
    "Time’s up! Can we get a moment of silence for our ambitions?",
    "Ding! The timer has made its grand entrance—how predictable!",
    "And just like that, the timer has called it quits. How inspiring!",
  ],
};

const getRandomMessage = () => {
  const messages = sarcasticMessages.messages;
  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
};

export default getRandomMessage;
